apiVersion: v1
kind: Pod
metadata:
  name: all-in-one-$testNum
spec:
  containers:
    - name: acc1
      image: docker-adobe-campaign-integro-snapshot.dr-uw2.adobeitc.com/acc-all-in-one:9122
      imagePullPolicy: Always
      stdin: true
      tty: true
      ports:
        - containerPort: 80
        - containerPort: 8080
      resources:
        requests:
          memory: "8G"
          cpu: "500m"
        limits:
          memory: "16G"
          cpu: "1"
    - name: integro-acc
      image: docker-adobe-campaign-integro-snapshot.dr-uw2.adobeitc.com/integro-v7-jar:v4
      stdin: true
      tty: true
      args:
        - $testMethod
  imagePullSecrets:
    - name: regcredqizhuintegro
  restartPolicy: Never
